FROM python:3.7.12-buster

WORKDIR /Weather-Classification

COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY . .
CMD ["sh", "-c", "streamlit run  app.py --server.port $PORT"] 